export const LOGIN_USER = 'login_user'
export const REGISTER_USER = 'register_user'
export const AUTH_USER = 'auth_user'
export const LOGOUT_USER = 'logout_user'
export const GET_USER_DETAIL = 'get_user_detail'
export const CLEAR_USER_DETAIL = 'clear_user_detail'
export const GET_FOLLOWING = 'get_following'
export const GET_FOLLOWER = 'get_follower'
export const FOLLOW = 'follow'
export const ADD_FOLLOWER = 'add_follower'
export const UNFOLLOW = 'unfollow'
export const REMOVE_FOLLOWER = 'remove_follower'
export const CLEAR_FOLLOWING = 'clear_following'
export const CLEAR_FOLLOWER = 'clear_follower'
export const GET_FOLLOWER_IN_LOAD_MORE = 'get_follower_in_load_more'
export const GET_FOLLOWING_IN_LOAD_MORE = 'get_following_in_load_more'

export const GET_DEPARTMENTS = 'get_departments'